### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by jianqiaoc** [erlzhang/erlsimple#1]
您好，看到您这个做的特别漂亮，我能拿来用吗？

**Comment by erlzhang** [comment]
可以，不限制使用及二次开发

**Comment by jianqiaoc** [comment]
谢谢，你太牛了，向你学习

**Comment by sharpain** [comment]
2月前又更新了吧,  style.css删了很多导致显示不正常啊,  百度网盘的旧版能正常显示, 盼主人看到并修复
