### ISSUE TITLE
:( Bug,bibibi

### ISSUE THREAD

**Issue by sky-rainy** [erlzhang/erlsimple#3]
评论BUG  那个更改 显示 VM999:1 Uncaught ReferenceError: toggleCommentAuthorInfo is not defined
找不到这个方法呢。。。

**Comment by sky-rainy** [comment]
@erlzhang  现在还弄这个么。。。

**Comment by erlzhang** [comment]
> 评论BUG 那个更改 显示 VM999:1 Uncaught ReferenceError: toggleCommentAuthorInfo is not defined
> 找不到这个方法呢。。。

wordpress版本是多少？

很久没有维护了，我最后使用的wordpress版本好像还是4.6，没有在新版本上测试过。

**Comment by sky-rainy** [comment]
刚看了下，WordPress 4.9.10 ，我只是刚开始用这个。。。以前没用过这个。。

**Comment by sky-rainy** [comment]
@erlzhang  你是在忙吗？ 现在上班呢？  等有空帮忙看下哈 谢了！ [地址](http://cloolc.club)

**Comment by erlzhang** [comment]
我知道了，不是版本的问题……

现在看自己两年前写的东西是真烂，莫名其妙……

https://github.com/erlzhang/erlsimple/commit/5c281826b811ccf3c6bf052fea485d0554113606 你把这个commit被删掉的代码恢复试一试？报错的原因是这个函数被删了，我也不记得为什么要删他……

我这里没有环境调试，估计要到周末能修复

**Comment by sky-rainy** [comment]
哈哈，很正常，自己写的东西1个月后再看你都感觉和现在相比差的太远了...代码加上了好使了，你应该是改什么东西忘了吧，以后commit提交写注释哈 养成好习惯哈！
还有两个问题， 文章第一次评论 报错 ajax-comment.js?ver=4.9.10:89 Uncaught TypeError: Cannot read property 'top' of undefined   ， 多次提交评论限制的时候ajax 没有提示被卡住了。。。   期待你周末哈！

**Comment by sky-rainy** [comment]
@erlzhang  期待你能加个音频播放器功能哈。

**Comment by erlzhang** [comment]
> 评论BUG 那个更改 显示 VM999:1 Uncaught ReferenceError: toggleCommentAuthorInfo is not defined

> 还有两个问题， 文章第一次评论 报错 ajax-comment.js?ver=4.9.10:89 Uncaught TypeError: Cannot read property 'top' of undefined ， 多次提交评论限制的时候ajax 没有提示被卡住了。。。 期待你周末哈！

这两个功能（大概也许可能）修复了，过一阵子有空的时候我可能会整体测试一下并重构一下代码
